### ISSUE TITLE
Use locale's Time Zone when provided

### ISSUE THREAD

**Issue by nfultz** [anufrievroman/calcure#43] opened 2023-02-23 22:07 UTC
I noticed that the calendar doesn't shift according to the locale's time zone, eg no difference when I launch as

    TZ=America/Los_Angeles calcure 

Compare vs other cli tools:

```
(venv) calcure$date
Thu 23 Feb 22:06:31 UTC 2023
(venv) calcure$TZ=America/Los_Angeles date
Thu 23 Feb 14:06:34 PST 2023

```

**Comment by anufrievroman** [comment] 2023-02-23 23:38
Yes, so far it doesn't care about timezones. I mean, for native calcure events there is no concept of "time" in calcure, only dates, so the "hours" are just text inside the title. However, I see that with .ics files it is a problem.

So, ideally, if in ics event the time is not "all day" we should try reading the timezone if provided, also read local timezone, and correct the time and date accordingly, right?

**Comment by nfultz** [comment] 2023-02-23 23:43
> So, ideally, if in ics event the time is not "all day" we should try reading the timezone if provided, also read local timezone, and correct the time and date accordingly, right?

I think that's a reasonable goal. At the minimum, I would want to adjust the day - UTC midnight is 4pm in my timezone, so evening events are showing up in the wrong box in the calendar.

**Comment by euglevi** [comment] 2023-09-24 11:37
Can I ask if there are news on this issue? This is literally the only thing preventing me to use calcure, which I find a great tool!

**Comment by anufrievroman** [comment] 2023-09-24 13:02
Hi, sorry for the delay. The problem is that it's more complex than I thought. I discovered as few issues actually:
1) `ics` library does not read the timezone, so I need to find a workaround to read it.
2) `ics` library (incorrectly) assumes that everything is in UTC. I guess that's what @nfultz meant above. This is a bug and should be fixed first.
3) Different calendars write their time zone differently, it seems. So, I'll need to investigate how to convert labels like "Asia/Tokyo" into actual hours value.

**Comment by anufrievroman** [comment] 2023-09-24 13:47
Okay, I at least fixed db8897db5c9dab4b51c6a124bc46071ebc57c288 the bug when the time was converted to UTC time and shown as such. This was the bug of `ics` library (that exists for many years), which I didn't realize existed. Now, if you stay in one timezone and make events in this timezone everything should work. Please update and test the version `1.9.5` from PyPi:

```
pipx upgrade calcure
```
Next step is to read the provided timezone somehow and correct time accordingly.

**Comment by euglevi** [comment] 2023-09-24 18:49
Thanks it is indeed much better this way! I can still see problems with timezones, but that solved most of the issues. By the way, I live in Italy.

**Comment by anufrievroman** [comment] 2023-11-24 08:28
This issue seems to be resolved, and now all timezones seem to convert to local timezones as expected. Please try to install the current main branch to test:
```
pipx install git+https://github.com/anufrievroman/calcure
```

**Comment by euglevi** [comment] 2023-11-24 09:44
I have tried and I confirm that, so far, the timezones seem to be correctly taken into consideration.

**Comment by anufrievroman** [comment] 2023-11-28 14:21
Okay, this seems to fully work now, so I'll close this issue.

**Closed by anufrievroman** 2023-11-28 14:21 UTC
Labels: Feature request
